/**
 * Class used to handle basic errors.
 */


var Error = function (errorType, errorText) {
	this.errType = errorType;
	this.errText = errorText;
}
Error.type = {
	GITHUB_ARCHIVE_DOWNLOAD_ERROR: "GITHUB_ARCHIVE_DOWNLOAD_ERROR",
	GITHUB_ARCHIVE_GUNZIP_ERROR: "GITHUB_ARCHIVE_GUNZIP_ERROR",
	ELASTIC_IS_DOWN: "ELASTIC_IS_DOWN",
	ELASTIC_CANNOT_CREATE_SNAPSHOT: "ELASTIC_CANNOT_CREATE_SNAPSHOT",
	ELASTIC_CANNOT_DELETE_SNAPSHOT: "ELASTIC_CANNOT_DELETE_SNAPSHOT",
	ELASTIC_CANNOT_RESTORE_SNAPSHOT: "ELASTIC_CANNOT_RESTORE_SNAPSHOT",
	ELASTIC_CANNOT_CREATE_SNAPSHOT_REPOSITORY: "ELASTIC_CANNOT_CREATE_SNAPSHOT_REPOSITORY",
	GIT_DATA_PUSHER_CALL_INIT_FIRST: "GITDATAPUSHER_CALL_INIT_FIRST",
	GIT_DATA_PUSHER_CANNOT_PUSH_EVENTS: "GIT_DATA_PUSHER_CANNOT_PUSH_EVENTS"
};

Error.prototype.toString = function() {
	return("Error type:" + this.errType + "\n" + "Description:" + this.errText);
}

module.exports = Error;